import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Providers } from "./providers";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const saved = localStorage.getItem('colorScheme');
                  const html = document.documentElement;
                  
                  // Always prioritize localStorage
                  if (saved) {
                    if (saved === 'dark') {
                      html.classList.add('dark');
                      html.style.colorScheme = 'dark';
                    } else {
                      html.classList.remove('dark');
                      html.style.colorScheme = 'light';
                    }
                  } else {
                    // Fallback to system preference only if nothing in localStorage
                    if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
                      html.classList.add('dark');
                      html.style.colorScheme = 'dark';
                    } else {
                      html.classList.remove('dark');
                      html.style.colorScheme = 'light';
                    }
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
